#!/bin/bash

set -e


remove_kdesudo() {
  if [ -e /usr/bin/kdesudo ]; then
    rm /usr/bin/kdesudo
  fi
}

case "$1" in
    remove|purge)
        remove_kdesudo
    ;;

    upgrade|abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
